"""
Multi-Agent AI System for Antigravity Builder.

Three specialized agents collaborate on each user prompt:
  1. Architect Agent  — designs the project structure and file layout
  2. Coder Agent      — generates the actual source code for each file
  3. Reviewer Agent   — reviews the code for bugs, security, and best practices

The Orchestrator chains them together and returns the final refined output.
"""

AGENT_PROMPTS = {
    "architect": (
        "You are the Architect Agent of Antigravity Builder. "
        "Given a user's app description, design the project structure. "
        "Output a JSON object with keys: project_name (string), type ('web' or 'android'), "
        "and file_list (array of relative file paths with a one-line description of each). "
        "Focus on clean architecture, separation of concerns, and scalability. "
        "Wrap your JSON in a ```json ... ``` code block."
    ),
    "coder": (
        "You are the Coder Agent of Antigravity Builder. "
        "You will receive a project architecture (file list with descriptions). "
        "Generate the complete source code for EVERY file listed. "
        "Output a JSON object with keys: project_name (string), type ('web' or 'android'), "
        "and files (object mapping each relative file path to its FULL source code as a string). "
        "Write production-quality, well-commented code. "
        "Wrap your JSON in a ```json ... ``` code block."
    ),
    "reviewer": (
        "You are the Code Reviewer Agent of Antigravity Builder. "
        "You will receive generated source code for a project. "
        "Review it for: bugs, security vulnerabilities, missing error handling, "
        "performance issues, and code style problems. "
        "Output a JSON object with keys: approved (boolean), issues (array of {file, line, severity, message}), "
        "and suggestions (array of strings for improvements). "
        "Wrap your JSON in a ```json ... ``` code block."
    )
}


def build_agent_messages(agent_name: str, user_content: str) -> list:
    """Build the chat messages list for a specific agent."""
    return [
        {"role": "system", "content": AGENT_PROMPTS[agent_name]},
        {"role": "user", "content": user_content}
    ]


async def run_agent(model, tokenizer, agent_name: str, user_content: str, max_tokens: int = 2048) -> str:
    """Run a single agent and return the raw text output."""
    import torch

    messages = build_agent_messages(agent_name, user_content)
    inputs = tokenizer.apply_chat_template(
        messages, return_tensors="pt", add_generation_prompt=True
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            inputs,
            max_new_tokens=max_tokens,
            temperature=0.7,
            top_p=0.8,
            repetition_penalty=1.05
        )

    reply_tokens = outputs[0][inputs.shape[-1]:]
    return tokenizer.decode(reply_tokens, skip_special_tokens=True)


async def orchestrate(model, tokenizer, user_prompt: str) -> dict:
    """
    Full multi-agent pipeline:
      1. Architect designs structure
      2. Coder generates code based on architecture
      3. Reviewer checks the code
    Returns combined results.
    """
    # Stage 1: Architect
    architecture = await run_agent(model, tokenizer, "architect", user_prompt, max_tokens=1024)

    # Stage 2: Coder (receives the architecture as context)
    coder_input = (
        f"Original user request: {user_prompt}\n\n"
        f"Architecture designed by Architect Agent:\n{architecture}\n\n"
        f"Now generate the complete source code for every file."
    )
    code_output = await run_agent(model, tokenizer, "coder", coder_input, max_tokens=4096)

    # Stage 3: Reviewer (receives the generated code)
    reviewer_input = (
        f"Project code generated by Coder Agent:\n{code_output}\n\n"
        f"Please review this code thoroughly."
    )
    review_output = await run_agent(model, tokenizer, "reviewer", reviewer_input, max_tokens=1024)

    return {
        "architecture": architecture,
        "code": code_output,
        "review": review_output,
        "pipeline": "architect → coder → reviewer"
    }
